close #33 任意の距離を直進・後退できる
KatLab-MiyazakiUniv/etrobocon2020 pull request #54
Opened 2020-08-19 03:00 UTC by YoshinoTakumi

## チェックリスト

- [ ] clang-format した
- [ ] コーディング規約に準じている
- [ ] テストに通った

## 変更点

- MoveStraightクラス を追加した

## 実機テストの結果（実機テストが必要な場合）

- スタートラインから590mmまでの距離（カーブの手前まで）を指定し、期待通りの走行をした

https://photos.app.goo.gl/8ted1z48cdqCvoDy5

2020-08-19 06:43 UTC, arimakaoru requested changes
調べた結果、ポインタ渡しよりも参照渡しが良さそう！

2020-08-19 06:43 UTC, arimakaoru commented on module/MoveStraight.h
> +  MoveStraight(Controller* cont_ptr_);
参照渡しにする
`MoveStraight(Controller& controller_);`

2020-08-19 06:43 UTC, arimakaoru commented on module/MoveStraight.cpp
> +      cont_ptr->setLeftMotorPwm(pwm);
参照渡しにすると、値渡しのときと同じ書き方ができる。
`controller.setLeftMotorPwm(pwm);`
他の場所も同じく。

2020-08-19 06:43 UTC, arimakaoru commented on module/MoveStraight.h
> +  void moveto(int destination, unsigned int pwm = 30);
コーディング規約より、単語の区切りを大文字にする
`void moveTo(...);`

2020-08-19 06:43 UTC, arimakaoru commented on module/MoveStraight.h
> +  Controller* cont_ptr;  // Controllerクラスポインタ
参照型にする
`Controller& controller;`

2020-08-19 06:43 UTC, arimakaoru commented on test/MoveStraightTest.cpp
> +}  // namespace etrobocon2020_test
- moveto関数の引数destinationに0を指定したときのテスト
- moveto関数の引数destinationにマイナスの値を指定したときのテスト
があるとさらに良いと思う

2020-08-19 06:43 UTC, arimakaoru commented on module/MoveStraight.h
> +   * @param destination 行き先（mm, 正で前進・負で後退）
「行き先」よりは「移動距離」とかの方がよくない？

2020-08-19 17:36 UTC, mutotaka0426 commented on module/MoveStraight.cpp
> +  int goal = presPos + destination;
LineTracer.cppとか他のコードもそうだけどDistance::getDistance()で得られる値はdouble型だから、距離の変数はdouble型の方がいいのでは？その方が多少精度も上がりそうだし

2020-08-21 00:53 UTC, arimakaoru commented on module/MoveStraight.h
> +#define BACK_BIAS 1  //後退の位置補正
これどういうこと？
後退のときは、1mmだけ補正が必要なの？

2020-08-21 07:35 UTC, merged