白黒以外の色までライントレースする関数と任意の色までライントレースする関数を追加
KatLab-MiyazakiUniv/etrobocon2020 pull request #61
Opened 2020-08-24 14:22 UTC by sugaken0528

## チェックリスト

- [ ] clang-format した
- [ ] コーディング規約に準じている
- [ ] テストに通った

## 変更点

- AAA を変更した

## 実機テストの結果（実機テストが必要な場合）

- 例: 10 回走行させた平均値を書く
- 例: 誤差率 [%] を書く
- 例: 前回の手法との差を書く

### 誤差率の計算式

誤差率 = （「測定値」 - 「理論値」） / 「理論値」 \* 100

2020-08-24 14:34 UTC, sugaken0528 commented
精度はちょっと微妙だけど一応止まる。

2020-08-25 02:01 UTC, arimakaoru requested changes
予想よりきれいに動くね！色識別の精度は今後の課題です。
ライントレーサー関係でリファクタリングしたいところが多いので、それは別チケットにしようと思います。

2020-08-25 05:03 UTC, arimakaoru approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/96624)

2020-08-25 05:47 UTC, mutotaka0426 approved these changes

2020-08-25 05:48 UTC, merged