白黒以外、任意の色を目指して直進する機能を追加
KatLab-MiyazakiUniv/etrobocon2020 pull request #68
Opened 2020-09-01 07:21 UTC by YoshinoTakumi

## チェックリスト

- [ ] clang-format した
- [ ] コーディング規約に準じている

## 変更点

- 白黒以外、任意の色を目指して直進する機能を追加した

## 実機テストの結果（実機テストが必要な場合）
白黒以外までの直進：chrome_oriented_running
任意の色までの直進：xxx_oriented_running
https://photos.app.goo.gl/8ted1z48cdqCvoDy5

2020-09-02 10:00 UTC, arimakaoru requested changes
スマホだとコードが見づらいから、見落としがあるかも

2020-09-03 01:05 UTC, korosuke613 commented on module/MoveStraight.cpp
> +      controller.tslpTsk(2000);  // 実機では4000に
実機とシミュレータで値を変えるならリテラルを入れるのではなく変数にして動的に変えられた方が良いのでは？
コンパイル時のオプションで変更できるようにするなりキャリブレーション時に変更できるようにするなり...
そうしないとしても、マジックナンバーになり得るから定数にするなりなんなりした方が良いとおもた

と思った。知らんけど

2020-09-03 01:39 UTC, arimakaoru commented on module/MoveStraight.cpp
> +      controller.tslpTsk(2000);  // 実機では4000に
たしかにマジックナンバーですね。
実は、シミュレータと実機の処理を分ける方法があります。
https://github.com/ETrobocon/etrobo/wiki/sim_ev3_src_change

ただ、これはControllerクラスに書くのが良いと思うので、別チケットにしましょう。
他のところのtslpTskもマジックナンバーになっているので、その対応も含めて。

つまり、今はこのままでいいよ！

2020-09-03 01:52 UTC, Tatsumi0000 requested changes
最終行の改行だけ気になりました！

2020-09-03 01:52 UTC, Tatsumi0000 commented on module/MoveStraight.cpp
> +}
ここ、最終行に改行が入ってないから入れておいたほうがいいかも。
GitHub上で見える、この赤いやつは、改行がないよ〜というWaringみたいなものだから。
それと、C++だとコンパイル時とかにWaring出なかったっけ？

2020-09-03 01:54 UTC, Tatsumi0000 reviewed
ここも！

2020-09-03 01:54 UTC, Tatsumi0000 commented on module/MoveStraight.h
> +#endif
ここもやね！

2020-09-03 02:07 UTC, Tatsumi0000 approved these changes
LOOKS GOOD TO ME !!!
![LGTM](https://cdn.lgtmoon.dev/images/97722)

2020-09-03 02:12 UTC, merged

2020-09-03 08:14 UTC, korosuke613 commented on module/MoveStraight.cpp
> +      controller.tslpTsk(2000);  // 実機では4000に
はえ〜すっごい。そんなことできるんや
がんばえ〜