Add: BlockBingoクラス
KatLab-MiyazakiUniv/etrobocon2020 pull request #69
Opened 2020-09-08 10:55 UTC by mutotaka0426

## チェックリスト

- [x] clang-format した
- [x] コーディング規約に準じている
- [x] テストに通った

## 変更点

- BlockBingoクラスの追加（経路計算を別のクラスにしたためこちらだけ先にコミットする）
- ブロックエリアの初期化する処理のみ実装
- ブロックエリアの初期化実装に伴いBlockBIngoDataに座標からサークルカラーを取得する関数を追加
- BlockBingoDataのinitをすべてsetに変更（initはBlockBingoクラスでする）

2020-09-08 10:57 UTC, sugaken0528 approved these changes

2020-09-08 13:48 UTC, arimakaoru requested changes
座標は、ブロックサークルと交点サークルに独立して割り当ててるの？
今日のミーティングの話だと、下図のようにブロックサークル、交点サークル、中点に連続した座標を割り当てている、という話じゃなかった？
![IMG_4774](https://user-images.githubusercontent.com/46063788/92484912-3a0f1480-f225-11ea-971c-3d92f3a0f1d1.JPG)

2020-09-08 13:48 UTC, arimakaoru commented on module/BlockBingo.cpp
> +                                 : blockBingoData.getCrossCircleColorR(i, j);
(オプション)
LRをまとめてもいいかも

2020-09-08 13:48 UTC, arimakaoru commented on module/BlockBingo.cpp
> +    for(i = 0; i < 4; i++) {
ん？交点サークルは、xとyが偶数の時じゃないの？
![IMG_4774](https://user-images.githubusercontent.com/46063788/92482837-0b903a00-f223-11ea-8461-01b2eac64ba0.JPG)

2020-09-08 13:48 UTC, arimakaoru commented on module/BlockBingo.cpp
> +    blockBingoData.setBlockCircle(x, y, tempBlockCircle);
いらないのでは？

2020-09-08 13:48 UTC, arimakaoru commented on module/BlockBingo.cpp
> +    blockBingoData.setCrossCircle(x, y, tempCrossCircle);
いらないのでは？

2020-09-08 13:55 UTC, arimakaoru commented on module/BlockBingo.cpp
> +    blockBingoData.setBlockCircle(x, y, tempBlockCircle);
これだけで良さそう
```
if((coordinate > 0) && (coordinate <= 8)) {
    blockBingoData.getBlockCircle(x, y).block.blockColor = initColor;
}
```

2020-09-08 14:06 UTC, Oiwane reviewed
動作に関してはさっぱりなので、コードを見て気になったところをいくつか挙げました。
反映しても動作は一切変化しないはずです。
反映するかどうかは、色々あると思うので、お好きにどうぞ。

2020-09-08 16:25 UTC, Tamiyas requested changes
気になったところを指摘しました。
仕様もミーティングの内容も完全に把握しているわけではないので、先輩だからといって恐れず
ガンガン反論してきてください 笑

2020-09-08 16:25 UTC, Tamiyas commented on module/BlockBingo.cpp
> +  this->initBlock(Color::black, controller.getCourseInfo(ETROBOC_COURSE_INFO_BLOCK_POS_BLACK1));
突然のthisでびっくりした（ただのコメント）

2020-09-08 16:25 UTC, Tamiyas commented on module/BlockBingo.cpp
> +  switch(coordinate) {
これはETロボコン側が用意したコース情報をデコードしているのかな？
この変換は、のちのち使いそうだから別関数としてまとめた方がよさそうじゃない？

その場合、やはり座標情報をもつBlockBingoDataが持つのが望ましい気がする。

2020-09-08 16:25 UTC, Tamiyas commented on module/BlockBingoData.cpp
> +  if((x >= 0) && (x < 2) && (y >= 0) && (y < 2)) {
あくまで一案なんだけど、
引数のx, yの範囲外チェック（0 <= x, y <= 4に収まっているか）だけ先にして、
あとは配列か何かに座標と結びつけた色情報を単純に返す関数にしてもいいんじゃないかな。

if文の連鎖を見ると気持ち悪くなっちゃう体質なもので...

2020-09-08 16:25 UTC, Tamiyas commented on module/BlockBingo.cpp
> +        tempBlockCircle = BlockCircle{ Color::none, BingoNumber::none, tempBlock };
それよりも `tempBlockCircle = { Color::none, BingoNumber::none, tempBlock }`で動かなかったのかどうかが、気になりました。

2020-09-08 19:09 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +    for(i = 0; i < 4; i++) {
今現在7×7で経路計算等はしてて、(x%2==1)&&(y%2==1)はブロックサークル、(x%2==0)&&(y%2==0)は交点サークルとして情報を取ってくるって感じでやってます。7×7に情報を入れてもよかったんですけど無駄が多いかなって思って。

確かに初期化はBlockBingoDataにかきほうがいい気がしてきました。変更します。

2020-09-08 19:10 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +  this->initBlock(Color::black, controller.getCourseInfo(ETROBOC_COURSE_INFO_BLOCK_POS_BLACK1));
this使わなくていいことにびっくりしました

2020-09-08 19:24 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +        tempBlockCircle = BlockCircle{ Color::none, BingoNumber::none, tempBlock };
ブロックが置かれてない時がColor::noneになってます。ブロックが置かれてないところも多いのでColor::noneを入れたほうがいいかと思います。

ちなみにtempBlockCircle = { Color::none, BingoNumber::none, tempBlock }で動きます。これのほうが見やすいのかなって思って書いてますけど、正直僕はどっちでもいいです。鬱陶しいって感じる人のほうが多いようなら消します。

2020-09-08 19:26 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +    blockBingoData.setBlockCircle(x, y, tempBlockCircle);
確かに！無駄な処理してました...

2020-09-08 19:45 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +    blockBingoData.setBlockCircle(x, y, tempBlockCircle);
と思いましたけど、それでブロックサークルの情報って変更されますか？setしないとBlockBingoData内の情報が書き換わらなくないですか？

2020-09-08 19:50 UTC, sugaken0528 commented on module/BlockBingo.cpp
> +  int i, j;  // i=x, j=y
これ武藤君が自分に説明してるときに書いたコメントがそのまま残ってるだけだと思います（笑）

2020-09-08 19:50 UTC, sugaken0528 commented on module/BlockBingo.cpp
> +    blockBingoData.setBlockCircle(x, y, tempBlockCircle);
同じくそんな気がします

2020-09-08 19:50 UTC, sugaken0528 commented on module/BlockBingo.cpp
> +    for(i = 0; i < 3; i++) {
独立してます🙆‍♂️

2020-09-08 19:51 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +    for(i = 0; i < 4; i++) {
経路計算とかは7×7の座標でやってるんですが、情報をセット、ゲットするときはブロックサークルは3×3の座標で、交点サークルは4×4の座標で取ってくるようにしてます。

ただ7×7では(2,4)なのに、情報を取ってくるときはクロスサークルの(1,2)から取ってくるのって、これを書いてる僕ら以外がすごく使いづらい気がしてきたので、どうしようかなって思ってます。BlockBingoDataのセッターとゲッターで7×7座標を受け取って変換してから処理をするようにしてもいいけど、その場合initの処理がだいぶ変わりそうな気がするし...

2020-09-08 19:55 UTC, sugaken0528 commented on module/BlockBingoData.cpp
> +    return Color::red;
同列の処理してるのでelse ifで書いた方が分かりやすいし見栄えも良いかなと思ってこの書き方にしてます😅

2020-09-08 19:55 UTC, mutotaka0426 commented on module/BlockBingo.h
> +   *  @brief
完全に見落としてました...ありがとうございます！

2020-09-08 19:59 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +                                 : blockBingoData.getCrossCircleColorR(i, j);
論破されました変更します

2020-09-08 20:01 UTC, sugaken0528 commented on module/BlockBingoData.h
> +  bool setBlockCircle(int x, int y, BlockCircle blockCircle);
修正しときます!

2020-09-08 20:05 UTC, sugaken0528 commented on module/BlockBingo.cpp
> +  int tempNumber;                                        // 数字カードの値を受け取る
確かにそうですね。もう少しマシな変数名考えます!

2020-09-08 20:22 UTC, sugaken0528 commented on module/BlockBingo.cpp
> +        tempBlockCircle = BlockCircle{ Color::none, BingoNumber::none, tempBlock };
ちなみに僕は見やすい派です

2020-09-08 20:25 UTC, mutotaka0426 commented on module/BlockBingoData.cpp
> +  if((x >= 0) && (x < 2) && (y >= 0) && (y < 2)) {
すみません、座標と結び付けた色情報というのがイメージができなかったです。4×4の2次配列とかに16通り用意しておいてそれを返すといった感じですか？

2020-09-09 00:00 UTC, Tamiyas commented on module/BlockBingo.cpp
> +  int i, j;  // i=x, j=y
そのまま`x, y`でいいってことじゃないかな。わざわざ`i. j`を使わなくてもよくない？

2020-09-09 00:09 UTC, Tamiyas commented on module/BlockBingo.cpp
> +  int tempNumber;                                        // 数字カードの値を受け取る
短い処理（スコープ）であれば、多少わかりにくい変数名であっても理解できます。例えば、for文のiとかswap関数のtempとか。
変数名のアンチパターンとして`temp`とか`info`とか`data`とかあって、
それらを修正して良い変数名にすることも大事だけど、処理を分けて行数を減らすことも大事ですよね。

2020-09-09 00:16 UTC, Tamiyas commented on module/BlockBingoData.cpp
> +  if((x >= 0) && (x < 2) && (y >= 0) && (y < 2)) {
そうそう！ 理解が早くて助かります。
特に配列でなくてもいいけど、色情報はまとめた方が読みやすいし`if`文も減るし良さそうかなと思っただけです。

2020-09-09 00:53 UTC, arimakaoru commented on module/BlockBingo.cpp
> +    blockBingoData.setBlockCircle(x, y, tempBlockCircle);
あ、C++はこれだと書き換えられないね！

2020-09-09 00:57 UTC, arimakaoru commented on module/BlockBingo.cpp
> +    for(i = 0; i < 4; i++) {
すごく分かりづらいと思う。
もしかして、7×7ではダメで、3×3や4×4の座標が必要なところがある？

2020-09-09 14:26 UTC, mutotaka0426 commented on module/BlockBingo.cpp
> +    for(i = 0; i < 4; i++) {
データの管理を3×3，4×4でやってるだけなので7×7でやったらダメってことはないですね．修正しておきます．

2020-09-09 15:02 UTC, mutotaka0426 commented on module/BlockBingoData.cpp
> +  if((x >= 0) && (x < 2) && (y >= 0) && (y < 2)) {
考えたのが，ヘッダーに
```
crossCircleColor[4][4]={{Color::blue, Color::blue, Color::red, Color::red},
                        {Color::blue, Color::blue, Color::red, Color::red},
                        {Color::green, Color::green, Color::yellow, Color::yellow},
                        {Color::green, Color::green, Color::yellow, Color::yellow} }
```
とかを定義してgetCrossCircleColorで
```
return crossCircleColor[y][x]
```
するみたいなのをLRでやる感じですか？

2020-09-12 02:27 UTC, arimakaoru requested changes
一箇所だけミスがあった。
他のところは良いと思う！

2020-09-12 02:27 UTC, arimakaoru commented on module/BlockBingoData.cpp
> +  if((circleNumber < 1) && (circleNumber > 8)) {
「1未満、または、8より大きいとき」だよね？
たぶん、getBlockCircleColor関数の異常時のテストが書かれていないと思う
```suggestion
  if((circleNumber < 1) || (circleNumber > 8)) {
```

2020-09-12 03:07 UTC, arimakaoru approved these changes
getBlockCircleColor関数の異常時のテストを追加するともっと良いけど！
![LGTM](https://cdn.lgtmoon.dev/images/99002)

2020-09-12 04:24 UTC, Tamiyas approved these changes
LGTM

2020-09-12 04:58 UTC, merged