経路計算クラスの追加
KatLab-MiyazakiUniv/etrobocon2020 pull request #72
Opened 2020-09-15 17:11 UTC by mutotaka0426

## チェックリスト

- [x] clang-format した
- [x] コーディング規約に準じている
- [x] テストに通った

## 変更点

- RouteCalcucatorクラスの追加
- BlockBingoData.hのBlockのコンストラクタを追加

2020-09-15 17:57 UTC, shigyo123 commented on module/RouteCalculator.cpp
> +  double actualCost;
ここがdouble型の理由を教えてください。

2020-09-15 17:57 UTC, shigyo123 approved these changes

2020-09-15 18:01 UTC, mutotaka0426 commented on module/RouteCalculator.cpp
> +  double actualCost;
intでした修正します

2020-09-17 07:30 UTC, arimakaoru approved these changes
よく頑張ったね〜 😳

![LGTM](https://cdn.lgtmoon.dev/images/99627)

2020-09-17 09:02 UTC, Tamiyas commented
このクラスを使うと何ができるのかを、もう少し書いていただけますか？
コースと計算で導かれた経路を具体例を使って示して頂けると、僕ら部外者もレビューしやすいです 🙏 

モデルに専念しているとのことなので、凝った説明ではなく、例えば手書きの画像1つあるだけで十分です。

2020-09-17 13:09 UTC, mutotaka0426 commented
> このクラスを使うと何ができるのかを、もう少し書いていただけますか？
> コースと計算で導かれた経路を具体例を使って示して頂けると、僕ら部外者もレビューしやすいです 🙏
> 
> モデルに専念しているとのことなので、凝った説明ではなく、例えば手書きの画像1つあるだけで十分です。

粗雑で申し訳ないですが，こんな感じでいかがでしょうか．
よろしくお願いします

![RouteCalculator](https://user-images.githubusercontent.com/56989154/93474391-3de01c80-f932-11ea-801c-8620f1de3d4f.png)

2020-09-17 14:45 UTC, Tamiyas commented
> 粗雑で申し訳ないですが，こんな感じでいかがでしょうか．
> よろしくお願いします

すごく読みやすい！ ありがとう！
ただ、レビューは明日の夜ぐらいになりそうです... ごめんね。

2020-09-18 12:51 UTC, Tamiyas requested changes
気になったことを指摘しました。
深くまで見れていない気がするので、トンチンカンなことを言ってるかもしれません...

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +        // printf("(%d,%d)は親ノードだから除外した\n", m.x, m.y);
親ノードは、`close`リストには入っていないの？

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +    close.push_back(elem);
`open`リストからノードを取り出した時点で、`close`リストに追加すればいいんじゃない？

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +        // printf("(%d,%d)は親ノードだから除外した\n", m.x, m.y);
ああ、`close`リストへの格納処理が下の方にあるのか

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +bool RouteCalculator::listCheck(AStarProperty node, vector<AStarProperty>& list)
副作用（`list.erase()`を呼び出している）がある処理を`listCheck()`と名付けるのはいかがなものか。
まぁ変えなくてもいいけど
少なくとも呼び出し元と関数のコメントには、副作用があることを明記した方がいいね。

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +        nx = x + i, ny = y + j;
おぉ、コンマ演算子！

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +int RouteCalculator::moveCost(int x, int y, int nx, int ny, Route route[7][7])
ちょっと... マジックナンバー多すぎないっすか！？

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +    printf("[ERROR] This coordinate does not pass.\n");
ここ、`printf`が残っているけど大丈夫？

2020-09-18 12:51 UTC, Tamiyas commented on test/RouteCalculatorTest.cpp
> +  TEST(RouteCalculator, solveBlockBingoData)
実際に経路計算させて、手計算と比較するみたいなことはしないの？

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +    list.push_back({ x, y });
ここで、エラーとなる座標をリストに入れるのは問題ないんだっけ？

2020-09-18 12:51 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +    setRoute(list, route, route[y][x].px, route[y][x].py);
ここで、再帰処理をすることで何が起こるのかを想像できなかった。何をしているのかを教えてくれますか？

2020-09-18 14:14 UTC, sugaken0528 commented on module/RouteCalculator.cpp
> +    setRoute(list, route, route[y][x].px, route[y][x].py);
![iOS の画像](https://user-images.githubusercontent.com/62526141/93607651-9384f980-fa04-11ea-908f-2fa8d91f0b51.jpg)

2020-09-18 15:10 UTC, sugaken0528 commented on module/RouteCalculator.cpp
> +    close.push_back(elem);
おそらくそれでも計算に問題はないと思いますけど、強いて言えば47行目の`close`リストから同じ座標を探すときに項目を1個増やすだけな気がするので利点を感じないのと、`open`リストから取り出した要素は計算が終わった後に`close`リストに追加するという認識だったんですけど、`open`リストから取り出した時点で`close`リストに追加する理由ってなんですか?

2020-09-18 15:17 UTC, mutotaka0426 commented on test/RouteCalculatorTest.cpp
> +  TEST(RouteCalculator, solveBlockBingoData)
有馬さんにも言われてたの忘れてました...
やりたいと思います。

2020-09-18 16:44 UTC, sugaken0528 commented on module/RouteCalculator.cpp
> +    list.push_back({ x, y });
ここはそもそも入れる必要がないですね!!
下にエラー分として出力できるようにしておきます

2020-09-18 16:46 UTC, sugaken0528 commented on module/RouteCalculator.cpp
> +    printf("[ERROR] This coordinate does not pass.\n");
ここはエラー文なので残してます

2020-09-23 09:04 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +    close.push_back(elem);
単純に38行目から40行目の「親ノードをopenリストに追加しない」の処理がなくなるのかなっと思っただけ。

2020-09-23 09:08 UTC, Tamiyas commented on module/RouteCalculator.cpp
> +    setRoute(list, route, route[y][x].px, route[y][x].py);
あっそうか。ごめんごめん。
`setRoute`が`solveBlockBingo`のwhileループの中にあると勘違いしてた。
わざわざ紙に書いて教えてくれてありがとね！

2020-10-13 04:54 UTC, arimakaoru approved these changes
LGTM

2020-10-13 07:51 UTC, sugaken0528 approved these changes

2020-10-15 00:00 UTC, arimakaoru approved these changes
OK!

2020-10-15 00:01 UTC, merged